apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edu-goods-hpa
  namespace: edu-goods
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edu-goods-deploy
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
