spring:
  application:
    name: edu-user
  profiles:
    active: loc

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true